spring:
  kafka:
    bootstrap-servers: kafka:9092 # Default to internal Docker address
    consumer:
      group-id: log-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
  redis:
    host: ${REDIS_HOST:redis}
    port: 6379

  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: log-consumer

ai:
  service:
    url: http://127.0.0.1:5000

server:
  port: 8082

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

